services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elasticsearch/certs:/usr/share/elasticsearch/config/certs
    networks:
      - internal
    ports:
      - "9200:9200"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: secure-shelter-siem-stack-kibana-1
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./config/elasticsearch/certs:/usr/share/kibana/config/certs:ro
    depends_on:
      - elasticsearch

  zeek:
    image: blacktop/zeek:latest
    container_name: zeek
    network_mode: host
    environment:
      - ZEEK_INTERFACE=${SNIFFING_INTERFACE}
      - ZEEK_SCRIPT_DIR=/config/zeek/scripts
    volumes:
      - ./data/zeek:/pcap
      - ./config/zeek:/config/zeek/scripts
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: unless-stopped

  suricata:
    image: jasonish/suricata:7.0.3
    container_name: suricata
    network_mode: host
    volumes:
      - ./config/suricata:/etc/suricata
      - ./data/suricata:/var/log/suricata
    environment:
      - SURICATA_OPTIONS=--af-packet=${SNIFFING_INTERFACE}
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    restart: unless-stopped

networks:
  internal:
    driver: bridge
